name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 生成浅色版贪吃蛇（仅保留支持的参数）
      - name: generate light snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: blackirlsama
          outputs: dist/github-contribution-grid-snake.svg
        env:
          # 用你的SNAKE_TOKEN，确保能访问私有仓库
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}

      # 推送文件到 output 分支
      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}